# Generated by Django 3.1.4 on 2020-12-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_picture/profile-default.png', upload_to='profile_picture/'),
        ),
    ]
