# Generated by Django 3.1.4 on 2020-12-05 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='position',
        ),
        migrations.AddField(
            model_name='listing',
            name='positions_available',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='listing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='organization.listing'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
