# Generated by Django 3.1.4 on 2020-12-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20201208_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='contract_type',
            field=models.CharField(blank=True, default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='cover_picture',
            field=models.ImageField(default='cover_picture/cover-pattern.jpg', upload_to='cover_picture/'),
        ),
    ]
