# Generated by Django 3.1.4 on 2020-12-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20201204_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.CharField(default='Provo, UT', max_length=50),
            preserve_default=False,
        ),
    ]
