# Generated by Django 3.1.4 on 2020-12-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_listing_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='contract_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(default='extended', max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='sectors',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='size',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
