# Generated by Django 3.1.4 on 2020-12-08 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_auto_20201207_1807'),
        ('organization', '0004_auto_20201207_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='organization',
        ),
        migrations.AddField(
            model_name='offer',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='applicant.application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contract_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='skills',
            field=models.ManyToManyField(blank=True, to='applicant.Skill'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='date_founded',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='sectors',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='organization',
            name='size',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
