# Generated by Django 3.1.4 on 2020-12-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20201207_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='compensation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
