# Generated by Django 3.1.4 on 2020-12-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20201208_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='date_founded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
