# Generated by Django 3.1.4 on 2020-12-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_auto_20201204_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='offer_made',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='skills',
            field=models.ManyToManyField(blank=True, to='applicant.Skill'),
        ),
    ]
