# Generated by Django 3.1.4 on 2020-12-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_auto_20201209_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_picture/profile-default.png', upload_to='profile_picture/'),
        ),
    ]
