# Generated by Django 3.1.4 on 2020-12-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_auto_20201208_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='about_me',
            field=models.TextField(blank=True),
        ),
    ]
