# Generated by Django 3.1.4 on 2020-12-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0006_auto_20201208_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
